### ISSUE TITLE
[Milestone] Deep Oasis Ocean Entities

### ISSUE THREAD

**Issue by northwesttreesgaming** [Space-Rift/Space-Rift#11]
The following list will be entities added to the Deep Oasis Ocean biome.
# ENTITIES
## WATER
- [X] Vampire Fish (Hostile)
- [X] Albino Vampire Fish (Hostile)
- [ ] Sea Star (Passive)
- [x] Jelly Fish (Netural)
- [ ] Blue Shark (Hostile)
## LAND
- [ ] Sand Hog (Pasive)
- [ ] Sand Crab (Netural)
- [ ] Clam (Passive)
- [ ] Night Stalker (Hostile)
- [ ] Evil Skull (Hostile)
## AIR
- [ ] Sea Bird (Passive)
- [ ] Avian Hunter (Agrssive)
- [ ] Sand Flapper (Nutural)
