### ISSUE TITLE
[Milestone] Deep Oasis Ocean Plants

### ISSUE THREAD

**Issue by northwesttreesgaming** [Space-Rift/Space-Rift#12]
# PLANTS
## WATER
- [X] Oasis Kelp
- [x] Oasis Sea Grass
- [x] Double Oasis Sea Grass
- [x] Oasis Glowweed
## LAND
- [X] Oasis Flowers
- [ ] Oasis Grass Blocks
- [ ] Dobule Oasis Grass Blocks
- [ ] Oasis Ferns
