### ISSUE TITLE
[Milestone] Deep Oasis Ocean Food

### ISSUE THREAD

**Issue by northwesttreesgaming** [Space-Rift/Space-Rift#15]
## FOOD
- [ ] Dried Kelp
- [ ] Raw Vampire Fish
- [ ] Cooked Vampire Fish
- [ ] Raw Shark
- [ ] Cooked Shark
- [ ] Shark Stew
- [ ] Vampire Fish Soup
- [ ] Oasis Sea Grain
- [ ] Oasis Bread
- [ ] Raw Clam
- [ ] Cooked Clam
- [ ] Clam Soup
- [ ] Raw Crab
- [ ] Cooked Crab
- [ ] Raw Sand Hog
- [ ] Cooked Sand Hog
