### ISSUE TITLE
[Milestone] Oasis Biomes

### ISSUE THREAD

**Issue by northwesttreesgaming** [Space-Rift/Space-Rift#5]
## BIOME LIST - PARADISE UPDAT
* [ ] Oasis Deadly Forest  ( Modified )
    A forest biome with more hostile life, plants that can hurt, and aggressive creatures. Poison lakes can be found here.
    
* [ ] Oasis Deep Ocean
    A deeper version of the basic ocean biome has water plants more dangerous entities and is far more deadly.
    
* [ ] Oasis Deep Ocean Reef ( Modified )
    A deeper version of the ocean reef biome has many water plants more dangerous entities and is far more deadly.
    
* [ ] Oasis Forest
    A tropical forest-based biome with palm trees many plants and grasses, much life can be found in this biome.
    
* [ ] Oasis Hills
    A tropical bumpy landscape with some highland life mostly a less dense area with more shrubs and hardy plants.
    
* [ ] Oasis Living Hills ( Modified )
    Same as the hills biome but with more life than rocks some trees can be found in this biome, unlike the other hill variant.
    
* [ ] Oasis Mineral Mountains ( Modified )
    A biome with abnormally high levels of minerals, not many plants grow here but you can find lots of rocks.
    
* [ ] Oasis Mountains
    A tropical high altitude biome that has mostly rocks and very little life.
    
* [ ] Oasis Ocean
    A shallow version of the basic ocean biome has water plants less dangerous entities and is far safer.
    
* [ ] Oasis Ocean Reef ( Modified )
    A shallow version of the ocean reef biome has many water plants less dangerous entities and is far safer.
    
* [ ] Oasis Plains
    A sandy grassland filled with plants and rocks, great for building as it's mostly flat.
    
* [ ] Oasis Plateau ( Modified )
    A sandy grassland filled with plants and rocks at a higher altitude, great for building as it's mostly flat.
