### ISSUE TITLE
[Milestone] Capture Pods

### ISSUE THREAD

**Issue by northwesttreesgaming** [Space-Rift/Space-Rift#8]
## About
Capture Pods will allow for bringing some creatures such as farm animals to dimensions in this mod from other worlds.

### Design textures
- [x] Empty capture pod texture
- [x] Cow capture pod texture
- [x] Chicken capture pod texture
- [x] Pig capture pod texture
- [x] Rabbit capture pod texture
- [x] Sheep capture pod texture
- [x] Wolf capture pod texture
- [x] Parrot capture pod texture
- [x] Cat capture pod texture
- [x] Horse capture pod texture
- [x] Donkey capture pod texture
- [x] Mule capture pod texture
- [x] Llama capture pod texture
- [x] Skeleton horse capture pot texture
- [x] Squid capture pod texture
- [x] Dolphins capture pod texture
- [x] Turtles capture pod texture
- [x] Tropical Fish capture pod texture
- [x] Puffer Fish capture pod texture
- [x] Cod capture pod texture
- [x] Salmon capture pod texture
- [x] Zombie Horse capture pod texture

### Create elements
- [x] Empty capture pod
- [x] Cow capture pod
- [x] Chicken capture pod
- [x] Pig capture pod
- [x] Rabbit capture pod
- [x] Sheep capture pod
- [x] Wolf capture pod
- [x] Parrot capture pod
- [x] Cat capture pod
- [x] Horse capture pod
- [x] Donkey capture pod
- [x] Mule capture pod
- [x] Llama capture pod
- [x] Skeleton horse capture pot
- [x] Squid capture pod
- [x] Dolphins capture pod
- [x] Turtles capture pod
- [x] Tropical Fish capture pod
- [x] Puffer Fish capture pod
- [x] Cod capture pod
- [x] Salmon capture pod
- [x] Zombie Horse capture pod

### Features
- [x] Save/Load entities with health
- [x] Save/Load entities with custom names
- [x] Support for tamed pets
- [x] Display if the creature is tamed
- [x] Display HP in item name
- [x] Display entity name in the item name
- [x] Support for farm animals
- [x] Cross world support
