### ISSUE TITLE
[Milestone] Deep Oasis Ocean

### ISSUE THREAD

**Issue by northwesttreesgaming** [Space-Rift/Space-Rift#9]
# FEATURES
### WATER
- [X] Vampire Fish (Hostile)
- [X] Albino Vampire Fish (Hostile)
- [ ] Sea Star (Passive)
- [x] Jelly Fish (Netural)
- [ ] Blue Shark (Hostile)
### LAND
- [ ] Sand Hog (Pasive)
- [ ] Sand Crab (Netural)
- [ ] Clam (Passive)
- [ ] Night Stalker (Hostile)
- [ ] Evil Skull (Hostile)
### AIR
- [ ] Sea Bird (Passive)
- [ ] Avian Hunter (Agrssive)
- [ ] Sand Flapper (Nutural)

### WATER
- [X] Oasis Kelp
- [x] Oasis Sea Grass
- [x] Double Oasis Sea Grass
- [x] Oasis Glowweed
### LAND
- [X] Oasis Flowers
- [ ] Oasis Grass Blocks
- [ ] Dobule Oasis Grass Blocks
- [ ] Oasis Ferns

## STUCTURES
- [x] Bones
- [ ] Plants
- [ ] Runins
- [ ] Bolders

## MINERALS
- [X] Ores
- [ ] Rocks
- [ ] Mineral Rocks

## FOOD
- [ ] Dried Kelp
- [ ] Raw/Cooked Vampire Fish
- [ ] Raw/Cooked Shark
- [ ] Shark Stew
- [ ] Vampire Fish Soup
- [ ] Oasis Sea Grain
- [ ] Oasis Bread
- [ ] Raw/Cooked Clam
- [ ] Clam Soup
- [ ] Raw/Cooked Crab
- [ ] Raw/Cooked Sand Hog
